# Deploy master with Google Container Registry
steps:

- name: 'node:10.7.0'
  entrypoint: npm
  args: ['install']

- name: 'node:10.7.0'
  entrypoint: npm
  args: ['run', 'build']

- name: 'node:10.7.0'
  entrypoint: npm
  args: ['run', 'build-storybook']

# upload
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'storybook-static', 'gs://unii-milkyway']

logsBucket: gs://striped-buckeye-163915_cloudbuild_logs
